storage: /verdaccio/storage/
plugins: /verdaccio/storage/
web:
  enable: true
  title: 私有 NPM 仓库
  gravatar: true
  login: true
  pkgManagers:
    - npm
    - yarn
    - pnpm
  html_cache: true
  showFooter: false
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: md5 # 这里选择 md5 作为加密算法
    max_users: -1 # 不允许自由注册
i18n:
  web: zh-CN

uplinks:
  taobao:
    url: https://registry.npmmirror.com
    cache: false

packages:
  "@*/*":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taobao
  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taobao

publishConfig:
  registry: http://localhost:4873/

middlewares:
  audit:
    enabled: true
listen: 0.0.0.0:4873
log: { type: stdout, format: pretty, level: http }
